enum ActionTypes {
  SHOW_TIMELINE_MOMENT_CONTEXTMENU = "view/SHOW_TIMELINE_MOMENT_CONTEXTMENU",
  HIDE_TIMELINE_MOMENT_CONTEXTMENU = "view/HIDE_TIMELINE_MOMENT_CONTEXTMENU",
  SHOW_TIMELINE_MOMENT_TOOLTIP = "view/SHOW_TIMELINE_MOMENT_TOOLTIP",
  UPDATE_TIMELINE_MOMENT_TOOLTIP = "view/UPDATE_TIMELINE_MOMENT_TOOLTIP",
  HIDE_TIMELINE_MOMENT_TOOLTIP = "view/HIDE_TIMELINE_MOMENT_TOOLTIP"
}

export default ActionTypes;
