enum ActionTypes {
  SET_MODE = "rating-editor/SET_MODE",
  SET_SELECTED_TIME_START = "rating-editor/SET_SELECTED_TIME_START",
  SET_SELECTED_TIME_END = "rating-editor/SET_SELECTED_TIME_END",
  SET_NEW_MOMENT_NAME = "rating-editor/SET_NEW_MOMENT_NAME",
  SET_NEW_MOMENT_DESCRIPTION = "rating-editor/SET_NEW_MOMENT_DESCRIPTION",
  SET_NEW_MOMENT_COLOR = "rating-editor/SET_NEW_MOMENT_COLOR",
  SET_NEW_MOMENT_REACTION = "rating-editor/SET_NEW_MOMENT_REACTION",
  SET_NEW_MOMENT_TIME_START = "rating-editor/SET_NEW_MOMENT_TIME_START",
  SET_NEW_MOMENT_TIME_END = "rating-editor/SET_NEW_MOMENT_TIME_END",
  SET_NEW_MOMENT_SECTION = "rating-editor/SET_NEW_MOMENT_SECTION",
  RESET_MOMENT_EDITOR = "rating-editor/RESET_MOMENT_EDITOR",
  SUBMIT_MOMENT_EDITOR = "rating-editor/SUBMIT_MOMENT_EDITOR",
  SEND_NEW_MOMENT_PENDING = "rating-editor/SEND_NEW_MOMENT_PENDING",
  SEND_NEW_MOMENT_REJECT = "rating-editor/SEND_NEW_MOMENT_REJECT",
  SEND_NEW_MOMENT_SUCCESS = "rating-editor/SEND_NEW_MOMENT_SUCCESS",
  SEND_NEW_MOMENT_ERROR = "rating-editor/SEND_NEW_MOMENT_ERROR",
}

export default ActionTypes;
